export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImRhbmllbCIsImVtYWlsIjoiZGFuaWVsQGVtYWlsLmNvbSIsImlhdCI6MTcwNjA0NzEwNywiZXhwIjoxNzA2NjUxOTA3LCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMSJ9.3nbRZXvb8PSPUvuHeem4ZcV5tRS7c1ha5rGnR4MeQhs';
